[package]
name = "veex-router"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ipnet.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
veex-core = { path = "../core" }

[dev-dependencies]
veex-test-tracing = { path = "../test-tracing" }
