[workspace]
members = [
    "crates/cli",
    "crates/config",
    "crates/core",
    "crates/dns",
    "crates/execution",
    "crates/infra-linux",
    "crates/portal-inbound",
    "crates/observability",
    "crates/portal-outbound",
    "crates/protocol",
    "crates/router",
    "crates/test-tracing",
    "crates/transport",
]
resolver = "2"

[workspace.package]
version = "0.7.0"
edition = "2024"
license = "MPL-2.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_path_to_error = "0.1"
serde_ignored = "0.1"
ipnet = "2"
humantime = "2"
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
rustls = "0.23"
rustls-native-certs = "0.8"
rustls-pemfile = "2"
tokio-rustls = "0.26"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "time",
    "local-time",
] }
time = { version = "0.3", features = ["macros"] }
sha2 = "0.10"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.release-dev]
inherits = "release"
debug = 1
strip = "none"
panic = "unwind"
