[workspace]
members = [
    "crates/cli",
    "crates/config",
    "crates/core",
    "crates/inbound-redirect",
    "crates/inbound-socks",
    "crates/observability",
    "crates/outbound-trojan",
    "crates/transport",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MPL-2.0"
version = "0.1.0"

[workspace.dependencies]
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
rustls = "0.23"
rustls-native-certs = "0.8"
rustls-pemfile = "2"
tokio-rustls = "0.26"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[profile.release-test]
inherits = "release"
debug = 1
strip = "none"
