[package]
name = "veex-outbound-trojan"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sha2.workspace = true
veex-core = { path = "../core" }
veex-transport = { path = "../transport" }
tokio.workspace = true

[dev-dependencies]
rcgen = "0.13"
rustls.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
veex-test-tracing = { path = "../test-tracing" }
