[package]
name = "veex-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "veex"
path = "src/main.rs"

[dependencies]
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
veex-config = { path = "../config" }
veex-core = { path = "../core" }
veex-dns = { path = "../dns" }
veex-execution = { path = "../execution" }
veex-portal-inbound = { path = "../portal-inbound" }
veex-observability = { path = "../observability" }
veex-portal-outbound = { path = "../portal-outbound" }
veex-router = { path = "../router" }
veex-transport = { path = "../transport" }
tokio.workspace = true

[dev-dependencies]
rcgen = "0.13"
rustls.workspace = true
tokio-rustls.workspace = true
veex-test-tracing = { path = "../test-tracing" }
