[package]
name = "veex-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "veex"
path = "src/main.rs"

[dependencies]
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
veex-config = { path = "../config" }
veex-core = { path = "../core" }
veex-inbound-direct = { path = "../inbound-direct" }
veex-inbound-transparent = { path = "../inbound-transparent" }
veex-inbound-socks = { path = "../inbound-socks" }
veex-observability = { path = "../observability" }
veex-outbound-direct = { path = "../outbound-direct" }
veex-outbound-trojan = { path = "../outbound-trojan" }
veex-transport = { path = "../transport" }
tokio.workspace = true

[dev-dependencies]
rcgen = "0.13"
rustls.workspace = true
tokio-rustls.workspace = true
veex-test-tracing = { path = "../test-tracing" }
