[package]
name = "veex-portal-inbound"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
veex-core = { path = "../core" }
veex-execution = { path = "../execution" }
veex-infra-linux = { path = "../infra-linux" }
