[package]
name = "veex-execution"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
veex-core = { path = "../core" }
veex-observability = { path = "../observability" }

[dev-dependencies]
veex-test-tracing = { path = "../test-tracing" }
