[package]
name = "veex-dns"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
tokio.workspace = true
tracing.workspace = true
veex-core = { path = "../core" }
veex-infra-linux = { path = "../infra-linux" }
veex-transport = { path = "../transport" }

[dev-dependencies]
veex-test-tracing = { path = "../test-tracing" }
