[package]
name = "veex-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
veex-observability = { path = "../observability" }

[dev-dependencies]
tracing-subscriber.workspace = true
veex-router = { path = "../router" }
veex-test-tracing = { path = "../test-tracing" }
