[package]
name = "veex-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ipnet.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
veex-observability = { path = "../observability" }

[dev-dependencies]
tracing-subscriber.workspace = true
veex-test-tracing = { path = "../test-tracing" }
