[package]
name = "veex-terminal"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
veex-signal = { path = "../veex-signal" }
veex-orbit = { path = "../veex-orbit" }
veex-echo = { path = "../veex-echo" }
veex-archive = { path = "../veex-archive" }
